platform :ios, '8.0'
use_frameworks!

target 'SwiftChromeActivity_Example', :exclusive => true do
  pod "SwiftChromeActivity", :path => "../"
end

target 'SwiftChromeActivity_Tests', :exclusive => true do
  pod "SwiftChromeActivity", :path => "../"
  pod 'FBSnapshotTestCase'
end
